try{
    let a;
    console.log(a.length);
    console.log("The control will never reach here");
}
catch{
    console.log("The control is inside the catch block");
}

console.log("This ends now");